<a href="https://colab.research.google.com/github/25wh1a0529/Nasscom-lab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
# 1. array creation functions
arr1 = np.arange(0, 10, 3)
print("Array using arange:", arr1)


Array using arange: [0 3 6 9]


In [18]:

arr2 = np.linspace(0,1,5)
print("Array using linspace:", arr2)


Array using linspace: [0.   0.25 0.5  0.75 1.  ]


In [25]:
arr3 = np.arange(1, 17).reshape((4, 4))
print("Reshaped Array (3x3):\n", arr3)
print("Flattened version:", arr3.flatten())

Reshaped Array (3x3):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Flattened version: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [30]:
# 2.aggregate functions
data=np.array([[1,4,9],[16,25,36]])
print("original data:\n",data)
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))
print("Standard Deviation:", np.std(data))

original data:
 [[ 1  4  9]
 [16 25 36]]
Sum of all elements: 91
Column-wise sum: [17 29 45]
Row-wise mean: [ 4.66666667 25.66666667]
Max value: 36
Index of max value (flattened): 5
Min value: 1
Standard Deviation: 12.212243401148248


In [33]:
# 3.sorting and seraching
a = np.array([3, 1, 7, 20, 100])
print("Original Array:", a)
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])

Original Array: [  3   1   7  20 100]
Sorted Array: [  1   3   7  20 100]
Indices where value > 4: (array([2, 3, 4]),)
Values > 4: [  7  20 100]


In [35]:
# 4.broadcasting in numpy
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print("Matrix A:\n", A)
print("Vector B:", B)
C = A + B
print("Broadcasted Addition Result:\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Vector B: [10 20]
Broadcasted Addition Result:
 [[11 22]
 [13 24]]


In [36]:
# 5.conditional operations
nums = np.array([1, 2, 3, 4, 5])
mask = nums > 3
print("Mask (nums > 3):", mask)
filtered = nums[mask]
print("Filtered values:", filtered)
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)

Mask (nums > 3): [False False False  True  True]
Filtered values: [4 5]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [37]:
# 6. copying vs viewing array
arr_orig = np.array([10, 20, 30])
arr_view = arr_orig[:]
arr_view[0] = 99
print("Original After View Change:", arr_orig)
arr_copy = arr_orig.copy()
arr_copy[0] = 55
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)

Original After View Change: [99 20 30]
Original After Copy Change: [99 20 30]
Copy: [55 20 30]


In [38]:
# 7. stacking and splitting
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [39]:
# 8. random numpy functions
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())


Random Integers:
 [[41 69 27]
 [14 62  7]
 [98 95 39]]
Random Normal Distribution:
 [[-0.87634032  0.49265105 -0.44511522 -1.95655303]
 [ 0.56447456 -0.57016533 -1.36873513 -1.72908944]]
Random Choices: [3 7 1 5 7]
Seeded Random Number: 0.3745401188473625


In [40]:
# 9. indexing and slicing with array
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])
print("Slice from index 1 to 4:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])


Original 1D Array: [10 20 30 40 50 60]
Element at index 0: 10
Element at last index: 60
Slice from index 1 to 4: [20 30 40]
Every second element: [10 30 50]
Reversed array: [60 50 40 30 20 10]


In [41]:
# 10. 2D array indexing and slicing
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Original Matrix:\n", matrix)
print("Element at (1,2):", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Top-left 2x2 block:\n", matrix[:2, :2])

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 block:
 [[1 2]
 [4 5]]


In [42]:
# 11 boolean indexing
arr = np.array([5, 10, 15, 20, 25, 30])
mask = arr > 15
print("Boolean Mask:", mask)
print("Values greater than 15:", arr[mask])
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])

Boolean Mask: [False False False  True  True  True]
Values greater than 15: [20 25 30]
Even numbers > 10: [20 30]
