<a href="https://colab.research.google.com/github/25wh1a0529/Nasscom-lab/blob/main/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr1_1 = np.arange(100)
print("arr1_1:\n",arr1_1)
arr1_2 = np.ones((3, 3))
print("arr1_2:\n",arr1_2)
arr1_3 = np.full((2, 4), 7)
print("arr1_3:\n",arr1_3)
arr1_4 = np.random.randint(10, 51, size=(5, 5))
print("arr1_4:\n",arr1_4)

arr1_1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4:
 [[11 49 26 18 37]
 [16 35 29 48 45]
 [50 21 12 24 29]
 [44 42 21 13 19]
 [27 15 34 34 28]]


In [ ]:
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])
val2_1 = data[2, 3]
print("val2_1\n",val2_1)
row2_2 = data[0]
print("row2_2:\n",row2_2)
col2_3 = data[:, -1]
print("col2_3:\n",col2_3)
sub_arr2_4 = data[1:3, 0:2]
print("sub_arr2_4:\n",sub_arr2_4)
filtered_elements2_5 = data[data > 100]
print("filtered_elements2_5:\n",filtered_elements2_5)


--- Task 2: Indexing and Slicing with Arrays ---
val2_1
 120
row2_2:
 [10 20 30 40]
col2_3:
 [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5:
 [110 120 130 140 150 160]


In [ ]:
print("Task 3: Conditional Operations")
arr3_1 = np.random.randint(1, 21, size=(4, 5))
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)
print("arr3_2:\n",arr3_2)
even_count3_3 = np.sum(arr3_1 % 2 == 0)
print("even_count3_3:\n",even_count3_3)

Task 3: Conditional Operations
arr3_2:
 [[ 0  0 16 15 11]
 [ 0 13 17 18 10]
 [11  0  0 19 18]
 [17 20  0  0  0]]
even_count3_3:
 10


In [ ]:
print("Task 4: Aggregation Functions")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])
sum4_1 = np.sum(arr4_1)
print("sum4_1:\n",sum4_1)
mean_cols4_2 = np.mean(arr4_1, axis=0)
print("mean_cols4_2:\n",mean_cols4_2)
max_rows4_3 = np.max(arr4_1, axis=1)
print("max_rows4_3:\n",max_rows4_3)
std4_4 = np.std(arr4_1)
print("std4_4:\n",std4_4)

Task 4: Aggregation Functions
sum4_1:
 84
mean_cols4_2:
 [11.          6.66666667 10.33333333]
max_rows4_3:
 [12 15 20]
std4_4:
 5.2493385826745405


In [ ]:
print("Task 5: Reshaping and Flattening")
arr5_1 = np.arange(24)
reshaped_arr5_2 = arr5_1.reshape(4, 6)
print("reshaped_arr5_2:\n",reshaped_arr5_2)
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
print("reshaped_arr5_3:\n",reshaped_arr5_3)
flattened_arr5_4_ravel = reshaped_arr5_2.ravel()
print("flattened_arr5_4_ravel:\n",flattened_arr5_4_ravel)
flattened_arr5_4  = reshaped_arr5_2.flatten()
print("flattened_arr5_4:\n",flattened_arr5_4)


Task 5: Reshaping and Flattening
reshaped_arr5_2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
reshaped_arr5_3:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
flattened_arr5_4_ravel:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
flattened_arr5_4:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [5]:
print("Task 6: Broadcasting")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])
result6_1 = arr6_1 + scalar
result6_2 = arr6_1 + vector

print("result6_1:\n",result6_1)
print("result6_2:\n",result6_2)

Task 6: Broadcasting
result6_1:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
result6_2:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [13]:
print("\nTask 7: Copying vs. Viewing Arrays")
original_arr7 = np.array([1, 2, 3, 4, 5])
view_arr7 = original_arr7[:]
view_arr7[0] = 99

print("Original array after modifying view:", original_arr7)
print("View array:", view_arr7)
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("Original array after modifying copy:", original_arr7)
print("Copy array:", copy_arr7)


Task 7: Copying vs. Viewing Arrays
Original array after modifying view: [99  2  3  4  5]
View array: [99  2  3  4  5]
Original array after modifying copy: [99  2  3  4  5]
Copy array: [99  2  3  4  0]


In [14]:
print("\nTask 8: Stacking and Splitting Arrays")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))
part1, part2, part3 = np.split(combined_arr8_3, [2, 4])

print("Vertical Stack:\n", vstack_arr8_1)
print("Horizontal Stack:\n", hstack_arr8_2)
print("Combined Array:\n", combined_arr8_3)
print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)


Task 8: Stacking and Splitting Arrays
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Combined Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Part 1:
 [[1 2]
 [3 4]]
Part 2:
 [[5 6]
 [7 8]]
Part 3:
 [[ 9 10]]


In [11]:
print("\nTask 9: Sorting and Searching")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])
sorted_arr9_1 = np.sort(arr9_1)
sorted_cols9_2 = np.sort(arr9_2d, axis=0)
idx9_3 = np.where(arr9_1 == 9)
max_idx9_4 = np.argmax(arr9_1)

print("Sorted 1D Array:", sorted_arr9_1)
print("Column-wise Sorted 2D Array:\n", sorted_cols9_2)
print("Index of value 9:", idx9_3)
print("Index of maximum value:", max_idx9_4)


Task 9: Sorting and Searching
Sorted 1D Array: [1 2 3 4 5 6 7 8 9]
Column-wise Sorted 2D Array:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]
Index of value 9: (array([4]),)
Index of maximum value: 4
