<a href="https://colab.research.google.com/github/25wh1a0529/Nasscom-lab/blob/main/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
print("\nTask 1: Basic Pandas Functions and Converting Arrays to DataFrames")
s1_1 = pd.Series([10, 20, 30, 40, 50])
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])
print(s1_1)
print(np_array1_2)
print(df1_3)


Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
0    10
1    20
2    30
3    40
4    50
dtype: int64
[[83 69 26 58]
 [77 78  9 49]
 [42  4 84 98]]
    A   B   C   D
0  83  69  26  58
1  77  78   9  49
2  42   4  84  98


In [12]:
import pandas as pd
import numpy as np

print("\nTask 2: Synthetic Data Generation for Practice")
df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', end='2023-04-10')[:100],
    'Region': np.random.choice(['East', 'West', 'North', 'South'], size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100),
    'Sales': np.random.randint(100, 1001, size=100).astype(float),
    'Quantity': np.random.randint(1, 11, size=100).astype(float)
})

sales_nan_indices = np.random.choice(df_sales.index, size=5, replace=False)
quantity_nan_indices = np.random.choice(df_sales.index, size=3, replace=False)

df_sales.loc[sales_nan_indices, 'Sales'] = np.nan
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan
print(df_sales.head())



Task 2: Synthetic Data Generation for Practice
        Date Region   Product  Sales  Quantity
0 2023-01-01   East     Mouse    NaN       3.0
1 2023-01-02   East  Keyboard  918.0       4.0
2 2023-01-03   East  Keyboard  418.0       2.0
3 2023-01-04   East     Mouse  394.0       7.0
4 2023-01-05  South     Mouse  862.0      10.0


In [13]:
print("\nTask 3: Indexing and Slicing in DataFrames")
df3_1 = df_sales[['Region', 'Sales']]
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]
monitor_index = df_sales[df_sales['Product'] == 'Monitor'].index[0]
val3_4 = df_sales.loc[monitor_index, 'Sales']
print(df3_1.head())
print(df3_2.head())
print(df3_3.head())
print("First Monitor Sales:", val3_4)


Task 3: Indexing and Slicing in DataFrames
  Region  Sales
0   East    NaN
1   East  918.0
2   East  418.0
3   East  394.0
4  South  862.0
         Date Region Product  Sales  Quantity
12 2023-01-13  South  Laptop    NaN       9.0
13 2023-01-14  South  Laptop  269.0       5.0
14 2023-01-15   West  Laptop  536.0       8.0
17 2023-01-18   East  Laptop  424.0       4.0
26 2023-01-27  South  Laptop  972.0       6.0
         Date Region   Product  Sales  Quantity
1  2023-01-02   East  Keyboard  918.0       4.0
5  2023-01-06   East     Mouse  901.0       5.0
10 2023-01-11   East     Mouse  792.0       5.0
15 2023-01-16   East   Monitor  891.0       9.0
25 2023-01-26   East  Keyboard  713.0       9.0
First Monitor Sales: 371.0


In [14]:
print("\nTask 4: Data Cleaning (Handling Missing Values)")
missing_counts4_1 = df_sales.isnull().sum()
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())
df4_3_dropped = df_sales.dropna()

print(missing_counts4_1)
print(df4_2_filled.head())
print(df4_3_dropped.head())



Task 4: Data Cleaning (Handling Missing Values)
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64
        Date Region   Product       Sales  Quantity
0 2023-01-01   East     Mouse  609.989474       3.0
1 2023-01-02   East  Keyboard  918.000000       4.0
2 2023-01-03   East  Keyboard  418.000000       2.0
3 2023-01-04   East     Mouse  394.000000       7.0
4 2023-01-05  South     Mouse  862.000000      10.0
        Date Region   Product  Sales  Quantity
1 2023-01-02   East  Keyboard  918.0       4.0
2 2023-01-03   East  Keyboard  418.0       2.0
3 2023-01-04   East     Mouse  394.0       7.0
4 2023-01-05  South     Mouse  862.0      10.0
5 2023-01-06   East     Mouse  901.0       5.0


In [16]:
print("\nTask 5: Data Manipulation (Columns, Sorting, Grouping)")
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'],
                                    ascending=[True, False])

df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print(df5_2_sorted.head())
print(df5_3_grouped_region)
print(df5_4_grouped_product)


Task 5: Data Manipulation (Columns, Sorting, Grouping)
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   East     Mouse    NaN       3.0            NaN
1 2023-01-02   East  Keyboard  918.0       4.0         3672.0
2 2023-01-03   East  Keyboard  418.0       2.0          836.0
3 2023-01-04   East     Mouse  394.0       7.0         2758.0
4 2023-01-05  South     Mouse  862.0      10.0         8620.0
          Sales  Quantity
Region                   
East    14202.0     130.0
North   14517.0     117.0
South   19134.0     175.0
West    10096.0     105.0
Product
Keyboard    621.384615
Laptop      569.772727
Monitor     553.388889
Mouse       665.413793
Name: Sales, dtype: float64
